<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
	<OutputType>Exe</OutputType>
	<Configurations>Debug;Release;TestRelease;TestDebug</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
	<PackageReference Include="xunit.v3" Version="4.0.1" />
	  <PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CachedEfCore.Caching.InMemory\CachedEfCore.Caching.InMemory.csproj" />
    <ProjectReference Include="..\..\src\CachedEfCore.DependencyInjection\CachedEfCore.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\CachedEfCore.SqlServer\CachedEfCore.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\CachedEfCore\CachedEfCore.csproj" />
    <ProjectReference Include="..\CachedEfCore.Tests.Common\CachedEfCore.Tests.Common.csproj" />
  </ItemGroup>

</Project>
