<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>CachedEfCore.SqlServer</Title>
		<PackageProjectUrl>https://www.nuget.org/packages/CachedEfCore.SqlServer</PackageProjectUrl>
		<Description>SqlServer database provider for CachedEfCore</Description>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CachedEfCore\CachedEfCore.csproj" />
	</ItemGroup>

</Project>
